### ISSUE TITLE
Not available in Canada

### ISSUE THREAD

**Issue by JoeMurray** [habitlab/HabitLabMobile#12]
Why does Google Play say the app is not available in my country? What is the advantage of excluding Canada? 

Where in the code is the exclusion? Would there be an issue if I forked the repo and submitted app so it could be installed and used in Canada?

**Comment by DrewGregory** [comment]
Hi @JoeMurray ! At last, I have published an app update. We now support signing into your Google account to sync data across devices (your email will be anonymized) and have fixed a lot of bugs. We will soon ship an update to the browser so that you can visualize your usage across different browsers and android devices under the same Google Account. Let me know if you run into any issues.

Thanks again for being so patient!

**Comment by JoeMurray** [comment]
Thanks
 I've installed and will be testing it out.
